# Generated by Django 4.0.2 on 2022-02-20 00:07

from django.db import migrations
from django.utils.text import slugify


def popular_slug(apps, schema_editor):
    Modulo = apps.get_model('modulos', 'Modulo')
    for modulo in Modulo.objects.all():
        modulo.slug = slugify(modulo.titulo)
        modulo.save()


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0002_modulo_slug_alter_modulo_id'),
    ]

    operations = [
        migrations.RunPython(popular_slug)
    ]
